install.packages("BiocManager")
BiocManager::install("preprocessCore")
BiocManager::install("affyPLM")
BiocManager::install("Biobase")
BiocManager::install("affy")

install.packages("XML")
install.packages("RCurl")
BiocManager::install("annotate")
BiocManager::install("genefilter")
BiocManager::install("sva")

install.packages('colorRamps',dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages('data.table',dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages('bapred',dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages('gplots',dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages('e1071',dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages('nnls',dependencies=TRUE, repos='http://cran.rstudio.com/')